### ISSUE TITLE
How to use only retrival component of semantic search (Information extraction)

### ISSUE THREAD

**Issue by theainerd** [semi-technologies/semantic-search-through-wikipedia-with-weaviate#2]
Hello i want to use this semantic search engine. I just want to retrive all documents rather performing question answering on it.
How to get the data of information retrival part using python client ?

**Comment by bobvanluijt** [comment]
You can!

### 1. Remove the Q&A module

* [Remove these lines](https://github.com/semi-technologies/semantic-search-through-wikipedia-with-weaviate/blob/main/step-3/docker-compose-gpu.yml#L43-L53)
* [Remove the config](https://github.com/semi-technologies/semantic-search-through-wikipedia-with-weaviate/blob/main/step-3/docker-compose-gpu.yml#L22)
* [Remove the module](https://github.com/semi-technologies/semantic-search-through-wikipedia-with-weaviate/blob/main/step-3/docker-compose-gpu.yml#L28)

### 2. Query using nearText

The [nearText](https://www.semi.technology/developers/weaviate/current/tutorials/how-to-perform-a-semantic-search.html#neartext-filter) function does a semantic search without the Q&A module.

For example:

```graphql
{
  Get {
    Paragraph(
      nearText: {
        concepts: ["Italian food"]
      }
      limit: 50
    ) {
      content
      order
      title
      inArticle {
        ... on Article {
          title
        }
      }
    }
  }
}
```

If you like, you can join our [Slack](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw) to further discuss this.

**Comment by theainerd** [comment]
Hello how exactly to use it using the python client, also i am trying to run on a cpu.

**Comment by bobvanluijt** [comment]
Hi @theainerd –

> how exactly to use it using the python client

You can connect the client to a Weaviate instance as outlined [here](https://www.semi.technology/developers/weaviate/current/client-libraries/python.html#installation-and-setup) in the docs. The above query will look something like:

```python
import weaviate

client = weaviate.Client("http://localhost:8080")

nearText = {
  "concepts": ["Italian food"]
}

client.query.get("Paragraph", ["content", "order", "title", "_additional {certainty} "]).with_near_text(nearText).limit(50).do()
```

> also i am trying to run on a CPU

This will work but slower and without the Q&A module, the docker file is [here](https://github.com/semi-technologies/semantic-search-through-wikipedia-with-weaviate/blob/main/step-3/docker-compose-no-gpu.yml)

**Comment by theainerd** [comment]
Strange but all i get is this error when i try to run.

ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by bobvanluijt** [comment]
Hi @theainerd – just to make sure, if you go to your browser and load: `http://localhost:8080/v1/meta` you can see the instance?

**Comment by theainerd** [comment]
I am running it on my gcp instance. I am trying to acess it : `http://<ip-of-the-machine>/v1/meta`
I am unable to access the instance. I am not sure what i am doing wrong.

Is there any further details i can share for further understanding of the problem.
