### ISSUE TITLE
Disambiguation improvements

### ISSUE THREAD

**Issue by loretoparisi** [semi-technologies/semantic-search-through-wikipedia-with-weaviate#3]
Hu guys, thanks for this outstanding work!
I was trying your GraphQL demo endpoint  and I had this disambiguation issue. For the query `Marc Marquez` (the moto racer) I'm getting the wrong document result,  while adding more context (like `motorcycle racer`) I get the correct result. Assumed that I cannot have for this item in the query more context, but "related wikipedia items" (let's say `Valentino Rossi`), is it possible to add a related item node embedding for this query?

```graphql
{
  Get {
    Paragraph(
      ask: {
        question: "Marc Marquez"
        properties: ["content"]
      }
      limit: 1
    ) {
      content
      order
      title
      inArticle {
        ... on Article {
          title
        }
      }
      _additional {
        answer {
          result
        }
      }
    }
  }
}
```

result:
```graphql
{
  "data": {
    "Get": {
      "Paragraph": [
        {
          "_additional": {
            "answer": {
              "result": null
            }
          },
          "content": "On November 10, 2017, Marquez was signed to the Detroit Lions' practice squad. He was promoted to the active roster on November 27, 2017. On September 11, 2018, Marquez was waived by the Lions. ",
          "inArticle": [
            {
              "title": "Bradley Marquez"
            }
          ],
          "order": 5,
          "title": "Detroit Lions"
        }
      ]
    }
  }
}
```

**Comment by bobvanluijt** [comment]
Hi @loretoparisi – sorry for the late response. I must have missed this question.

> is it possible to add a related item node embedding for this query?

I'm not 100% sure I understand, can you please elaborate a bit more?

**Comment by bobvanluijt** [comment]
Btw – you might also like to join our [Slack](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw) channel.

**Comment by loretoparisi** [comment]
> Hi @loretoparisi – sorry for the late response. I must have missed this question.
> 
> 
> 
> > is it possible to add a related item node embedding for this query?
> 
> 
> 
> I'm not 100% sure I understand, can you please elaborate a bit more?

Thanks for your help! So, since using the bare query `Marc Marquez` the result is wrong, while adding more context (like `
motor racer
`) it works ok, I was wondering if it is possible to add this context not as text, but as en embedding representation (let's say using the wikidata property for pilot or motor racer, etc.).

**Comment by bobvanluijt** [comment]
That's an interesting idea @loretoparisi, thanks – I've moved the discussion [here](https://github.com/semi-technologies/weaviate/issues/1777).
